language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script: bundle exec rake lint && bundle exec rake spec
env:
  - PUPPET_VERSION=2.6.9
  - PUPPET_VERSION=2.7.14
  - PUPPET_VERSION=2.7.19
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.9
